// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Build/install үед DATABASE_URL байхгүй орчинд `prisma generate` унахгүй байлгах fallback.
    url:
      process.env["DATABASE_URL"] ??
      "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
